### ISSUE TITLE
Error Can't install dwelch2101/dropbox-sync-armv7:1.3.0

### ISSUE THREAD

**Issue by KrisRux** [danielwelch/hassio-addons#3]
i have a problem to install a component:

19-03-08 13:29:42 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/danielwelch/hassio-addons repository
19-03-08 13:29:44 INFO (MainThread) [hassio.addons] Load add-ons: 53 all - 1 new - 0 remove
19-03-08 13:29:51 INFO (MainThread) [hassio.addons.addon] Create Home Assistant add-on data folder /data/addons/data/7be23ff5_dropbox_sync
19-03-08 13:29:51 INFO (SyncWorker_6) [hassio.docker.interface] Pull image dwelch2101/dropbox-sync-armv7 tag 1.3.0.
19-03-08 13:29:53 ERROR (SyncWorker_6) [hassio.docker.interface] Can't install dwelch2101/dropbox-sync-armv7:1.3.0 -> 404 Client Error: Not Found ("pull access denied for dwelch2101/dropbox-sync-armv7, repository does not exist or may require 'docker login'").

**Comment by danielwelch** [comment]
see https://github.com/danielwelch/hassio-zigbee2mqtt/issues/123

**Comment by KrisRux** [comment]
can you fix also dropbox-sync?

**Comment by danielwelch** [comment]
Done, let me know if you keep having problems.
